<!-- Page Footer -->
    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; <?=date("Y");?> NETOPIA Payments</p>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="https://netopia-payments.com/contact-suport/" target="_blank">Support</a></li>
        </ul>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="theme/js/theme.js"></script>
    <script src="theme/js/3DS.js"></script>
    <script src="theme/js/custom.js"></script>
