<!-- Page Nav -->
    <div class="row">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Make Payment</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="realTimeLog-tab" data-toggle="tab" href="#realTimeLog" role="tab" aria-controls="realTimeLog" aria-selected="false">Real time log</a>
            </li>
        </ul>
    </div>