<!-- Page Top Nav -->
    <div class="py-5">
        <a href="<?=$_ENV['PROJECT_SERVER_ADDRESS'].$_ENV['PROJECT_BASE_ROOT']?>">
            <img class="d-block mx-auto mb-4" src="<?=$_ENV['PROJECT_LOGO']?>" alt="<?=$_ENV['PROJECT_AUTHOR']?>" width="200">
        </a>
        <h1><?=$_ENV['PROJECT_TITLE']?></h1>
        <p class="lead"><?=$_ENV['PROJECT_DESCRIPTION']?></p>
        <h2><?=$_ENV['PROJECT_VERSION']?></h2>
    </div>